# Generated by Django 5.2.5 on 2025-08-11 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('POLL_CREATED', 'Poll Created'), ('POLL_EXPIRED', 'Poll Expired'), ('GROUP_FORMED', 'Group Formed'), ('DEAL_COMPLETED', 'Deal Completed'), ('CONTRACT_OFFER', 'Contract Offer'), ('SYSTEM_UPDATE', 'System Update')], max_length=20)),
                ('title_template', models.CharField(max_length=255)),
                ('message_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('POLL_CREATED', 'Poll Created'), ('POLL_EXPIRED', 'Poll Expired'), ('GROUP_FORMED', 'Group Formed'), ('DEAL_COMPLETED', 'Deal Completed'), ('CONTRACT_OFFER', 'Contract Offer'), ('SYSTEM_UPDATE', 'System Update')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('related_deal_group_id', models.IntegerField(blank=True, null=True)),
                ('related_poll_id', models.IntegerField(blank=True, null=True)),
                ('related_contract_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
