# Generated by Django 5.2.4 on 2025-08-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_deal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_hub_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('POLL_CREATED', 'Poll Created'), ('POLL_EXPIRED', 'Poll Expired'), ('GROUP_FORMED', 'Group Formed'), ('DEAL_COMPLETED', 'Deal Completed'), ('CONTRACT_OFFER', 'Contract Offer'), ('SYSTEM_UPDATE', 'System Update'), ('HUB_SELECTED', 'Hub Selected'), ('ESCROW_DEPOSITED', 'Escrow Deposited'), ('SHIPMENT_BOOKED', 'Shipment Booked'), ('PAYOUT_RELEASED', 'Payout Released')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('POLL_CREATED', 'Poll Created'), ('POLL_EXPIRED', 'Poll Expired'), ('GROUP_FORMED', 'Group Formed'), ('DEAL_COMPLETED', 'Deal Completed'), ('CONTRACT_OFFER', 'Contract Offer'), ('SYSTEM_UPDATE', 'System Update'), ('HUB_SELECTED', 'Hub Selected'), ('ESCROW_DEPOSITED', 'Escrow Deposited'), ('SHIPMENT_BOOKED', 'Shipment Booked'), ('PAYOUT_RELEASED', 'Payout Released')], max_length=20),
        ),
    ]
