# Generated by Django 5.2.5 on 2025-08-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=100, unique=True)),
                ('total_quantity_kg', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('FORMED', 'Formed'), ('NEGOTIATING', 'Negotiating'), ('SOLD', 'Sold'), ('EXPIRED', 'Expired')], default='FORMED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(to='products.productlisting')),
            ],
        ),
    ]
