# Generated by Django 5.2.5 on 2025-08-10 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_negotiationmessage'),
        ('hubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealgroup',
            name='recommended_collection_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hubs.hubpartner'),
        ),
    ]
