# Generated by Django 5.2.5 on 2025-08-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_dealgroup_recommended_collection_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
