# Generated by Django 5.2.5 on 2025-08-10 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_groupmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NegotiationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rounds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_sessions', to=settings.AUTH_USER_MODEL)),
                ('deal_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_sessions', to='deals.dealgroup')),
            ],
            options={
                'unique_together': {('deal_group', 'buyer')},
            },
        ),
    ]
