# Generated by Django 5.2.5 on 2025-08-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0008_negotiationsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationsession',
            name='last_counter_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
