# Generated by Django 5.2.5 on 2025-08-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0010_deallineitem_dealrating_deliveryreceipt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negotiationsession',
            name='floor_price',
        ),
        migrations.RemoveField(
            model_name='negotiationsession',
            name='rounds',
        ),
        migrations.RemoveField(
            model_name='negotiationsession',
            name='target_price',
        ),
        migrations.AddField(
            model_name='negotiationsession',
            name='negotiation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(db_index=True, max_length=100)),
                ('region', models.CharField(db_index=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(db_index=True)),
                ('source', models.CharField(default='CSV_Import', max_length=50)),
                ('quality_grade', models.CharField(blank=True, max_length=20, null=True)),
                ('volume_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'ordering': ['-date', 'crop_name'],
                'indexes': [models.Index(fields=['crop_name', 'region', 'date'], name='deals_marke_crop_na_31c2ea_idx'), models.Index(fields=['crop_name', 'date'], name='deals_marke_crop_na_833089_idx'), models.Index(fields=['region', 'date'], name='deals_marke_region_e398a6_idx')],
            },
        ),
    ]
