# Generated by Django 5.2.5 on 2025-08-13 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0011_remove_negotiationsession_floor_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISessionMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('conversation_history', models.JSONField(default=list, help_text='List of message IDs in conversation order')),
                ('farmer_questions', models.JSONField(default=list, help_text='Questions asked by farmers')),
                ('ai_responses', models.JSONField(default=list, help_text='AI agent responses given')),
                ('current_market_analysis', models.JSONField(default=dict, help_text='Current market analysis for the group')),
                ('pricing_decisions', models.JSONField(default=list, help_text='Pricing decisions made and explained')),
                ('trust_building_moments', models.JSONField(default=list, help_text='Key moments that build trust')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='ai_response_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_responses', to='deals.groupmessage'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='category',
            field=models.CharField(choices=[('general_chat', 'General Chat'), ('pricing_discussion', 'Pricing Discussion'), ('logistics_info', 'Logistics Information'), ('market_insights', 'Market Insights'), ('decision_guidance', 'Decision Guidance'), ('trust_building', 'Trust Building')], default='general_chat', max_length=20),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='farmer_reactions',
            field=models.JSONField(blank=True, default=dict, help_text='Farmer reactions (👍, 👎, etc.)'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='hub_details',
            field=models.JSONField(blank=True, default=dict, help_text='Common hub and logistics details'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='is_ai_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pin important messages'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='market_data_summary',
            field=models.JSONField(blank=True, default=dict, help_text='Summary of market data used'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='message_type',
            field=models.CharField(choices=[('farmer_message', 'Farmer Message'), ('ai_agent_message', 'AI Agent Message'), ('system_announcement', 'System Announcement'), ('price_explanation', 'Price Explanation'), ('hub_details', 'Hub Details'), ('market_analysis', 'Market Analysis')], default='farmer_message', max_length=20),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='narrative_story',
            field=models.TextField(blank=True, help_text='Detailed narrative explanation for farmers'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='session_id',
            field=models.CharField(blank=True, help_text='Session ID for conversation continuity', max_length=100),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='trust_indicators',
            field=models.JSONField(blank=True, default=dict, help_text='Data points to build trust'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='groupmessage',
            index=models.Index(fields=['deal_group', 'session_id'], name='deals_group_deal_gr_6b42aa_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessage',
            index=models.Index(fields=['deal_group', 'is_ai_agent'], name='deals_group_deal_gr_f7c195_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessage',
            index=models.Index(fields=['deal_group', 'category'], name='deals_group_deal_gr_fe17a6_idx'),
        ),
        migrations.AddField(
            model_name='aisessionmemory',
            name='deal_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to='deals.dealgroup'),
        ),
        migrations.AddIndex(
            model_name='aisessionmemory',
            index=models.Index(fields=['deal_group', 'session_id'], name='deals_aises_deal_gr_3985e5_idx'),
        ),
        migrations.AddIndex(
            model_name='aisessionmemory',
            index=models.Index(fields=['session_id', 'is_active'], name='deals_aises_session_9498ef_idx'),
        ),
    ]
