# Generated by Django 5.2.4 on 2025-08-14 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0012_aisessionmemory_groupmessage_ai_response_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='farmer',
            new_name='voter',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('poll', 'voter')},
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_type',
            field=models.CharField(choices=[('price_offer', 'Price Offer'), ('location_confirmation', 'Location Confirmation')], default='price_offer', max_length=25),
        ),
        migrations.AlterField(
            model_name='poll',
            name='buyer_offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='offering_buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.CharField(choices=[('ACCEPT', 'Accept'), ('REJECT', 'Reject'), ('YES', 'Yes'), ('NO', 'No')], max_length=10),
        ),
    ]
