# Generated by Django 5.2.5 on 2025-08-10 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('products', '0003_productlisting_grade_confidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='forwardcontract',
            old_name='delivery_end_date',
            new_name='delivery_window_end',
        ),
        migrations.RenameField(
            model_name='forwardcontract',
            old_name='delivery_start_date',
            new_name='delivery_window_start',
        ),
        migrations.RenameField(
            model_name='forwardcontract',
            old_name='quantity_required_kg',
            new_name='max_qty_kg',
        ),
        migrations.RemoveField(
            model_name='forwardcontract',
            name='is_public',
        ),
        migrations.AddField(
            model_name='forwardcontract',
            name='advance_pct',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Advance payment percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='forwardcontract',
            name='grade',
            field=models.CharField(default='TBD', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forwardcontract',
            name='min_qty_kg',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forwardcontract',
            name='region',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forwardcontract',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('FILLED', 'Filled'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='forwardcontract',
            name='terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='forwardcontract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='forwardcontract',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.cropprofile'),
        ),
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('external_ref', models.CharField(blank=True, help_text='Payment gateway reference', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_payments', to='contracts.forwardcontract')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContractCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committed_qty_kg', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_commitments', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='contracts.forwardcontract')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_commitments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FarmerCommitment',
        ),
    ]
