# Generated by Django 5.2.5 on 2025-08-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_rename_delivery_end_date_forwardcontract_delivery_window_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwardcontract',
            name='advance_pct',
            field=models.DecimalField(decimal_places=2, help_text='Advance payment percentage', max_digits=5),
        ),
    ]
