# Generated by Django 5.2.5 on 2025-08-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropprofile',
            name='min_group_kg',
            field=models.PositiveIntegerField(default=10000, help_text='Minimum total kg required to form a deal group'),
        ),
    ]
