# Generated by Django 5.2.5 on 2025-08-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cropprofile_min_group_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='grade_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='grading_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='grading_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('GROUPED', 'Grouped'), ('SOLD', 'Sold'), ('GRADING', 'Grading')], default='AVAILABLE', max_length=20),
        ),
    ]
