# Generated by Django 5.2.5 on 2025-08-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productlisting_grade_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('GROUPED', 'Grouped'), ('ACCEPTED', 'Accepted (Awaiting Escrow)'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('PAID', 'Paid'), ('SOLD', 'Sold'), ('GRADING', 'Grading')], default='AVAILABLE', max_length=20),
        ),
    ]
