# Generated by Django 5.2.5 on 2025-08-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productlisting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropprofile',
            name='is_supported',
            field=models.BooleanField(default=True, help_text='Whether this crop is supported by BIG_DATA.csv'),
        ),
    ]
