# Generated by Django 5.2.5 on 2025-08-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_add_is_supported_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropprofile',
            name='is_supported',
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='grade',
            field=models.CharField(choices=[('FAQ', 'FAQ'), ('Medium', 'Medium'), ('Large', 'Large'), ('Local', 'Local'), ('Non-FAQ', 'Non-FAQ'), ('Ref grade-1', 'Ref grade-1'), ('Ref grade-2', 'Ref grade-2')], max_length=20),
        ),
    ]
