# Generated by Django 5.2.5 on 2025-08-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0002_customuser_first_name_customuser_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='primary_crops',
            field=models.ManyToManyField(blank=True, related_name='primary_farmers', to='products.cropprofile'),
        ),
    ]
